### ISSUE TITLE
Exception in thread "main" com.nexmo.client.NexmoResponseParseException: Unable to parse response.

### ISSUE THREAD

**Issue by tomimoolan** [Nexmo/nexmo-java#264] opened 2019-08-22 16:07 UTC
I am getting the following error 
Exception in thread "main" com.nexmo.client.NexmoResponseParseException: Unable to parse response.
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:107)
	at com.nexmo.client.sms.SmsClient.submitMessage(SmsClient.java:79)
	at gm.nexmo.SendMessage.main(SendMessage.java:23)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to rest.nexmo.com:443 [rest.nexmo.com/169.63.86.163] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:102)
	... 2 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 13 more

I copied the code from nexmo site. Do I need to use proxy server?

<img width="488" alt="Capture111" src="https://user-images.githubusercontent.com/54410575/63530891-5c78a780-c4d5-11e9-9c86-0f62890ea090.PNG">

**Comment by SevrainChea** [comment] 2019-10-10 12:57
Hello same error here, some help would be good

**Comment by dragonmantank** [comment] 2020-03-16 15:53
Hello!

Sorry for the long wait on this, but in case you haven't reached out to support or our community Slack channel I wanted to hopefully provide some help. 

Can you let us know what version of Java and the SDK that you are currently running? 

The error you are seeing is from when the SDK cannot parse the result from the API call. Normally this means that somewhere along the line there is an issue communicating with our API, before it reaches our server. 

I see in the stacktrace that you are getting "Connection refused", so this looks like a networking issue. This either means that there is a routing issue from your machine to our API, or there is something blocking access to our API, which could be a firewall or a proxy. If you have a proxy, you may need to supply a custom HTTP Client to the Nexmo class that calls the proxy.

Make sure that you can reach `https://rest.nexmo.com/sms/json` from your development machine or the machine that is getting this error. You can also try our cURL option at https://developer.nexmo.com/messaging/sms/code-snippets/send-an-sms/curl to see if even a basic API call works.

**Comment by Amiko** [comment] 2020-03-24 15:43
Same issue here. Exception rises periodically. Using java 8.
Any proper feedback would be good.

**Comment by sasagonz** [comment] 2020-06-17 17:34
We are having similar issue. Sometimes we get this error:

Caused by: com.nexmo.client.NexmoResponseParseException: Unable to parse response.#
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:107)#
	at com.nexmo.client.sms.SmsClient.submitMessage(SmsClient.java:79)#
	at xxxx.NexmoSmsProvider.sendSMS(NexmoSmsProvider.java:46)#
	...	
#Caused by: java.net.SocketException: Connection reset#
	at java.net.SocketInputStream.read(SocketInputStream.java:210)#
	at java.net.SocketInputStream.read(SocketInputStream.java:141)#
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)#
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)#
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)#
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)#
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)#
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)#
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)#
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)#
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)#
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)#
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)#
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)#
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)#
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)#
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)#
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)#
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)#
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)#
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)#
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)#
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)#
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)#
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)#
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:102)#	... 119 more#

We create the SmsClient class as attribute of a CDI singleton bean. Most of the times, SMS is sent. But we also have many errors as above. We're using Java8 and version 5.2.1 of nexmo client library.

**Comment by vinokanth92** [comment] 2020-07-26 08:13
Is there a update on this? It happening frequently when terminating call.

**Comment by yallen011** [comment] 2020-07-31 16:19
@vinokanth92 I do not think your issue is related to this one since you are referring to voice and this issue is for SMS.

**Comment by yallen011** [comment] 2020-07-31 21:17
@sasagonz  are you still having this issue?

**Comment by yallen011** [comment] 2020-07-31 21:30
closing this issue as I was unable to reproduce this error given a CA virtual nexmo number and a US mobile number. If you are still seeing this error, please open an issue for your specific error with more details using the new **Bug report** template we have for reporting issues and we will investigate.

**Closed** 2020-07-31 21:31 UTC
Labels: Resolution: Cannot Reproduce
