### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException on CANCELLED calls

### ISSUE THREAD

**Issue by nivanov85** [Nexmo/nexmo-java#69] opened 2017-07-07 14:25 UTC
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.nexmo.client.voice.CallStatus, problem: No enum constant com.nexmo.client.voice.CallStatus.CANCELLED

**Comment by judy2k** [comment] 2017-07-27 08:09
This is a more specific duplicate of #68

**Closed by judy2k** 2017-07-27 08:09 UTC
Labels: Resolution: Duplicate
